import "./globals.css";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <header className="bg-gray-100 p-4">Header</header>
        {children}
        <footer className="bg-red p-4">Footer</footer>
      </body>
    </html>
  );
}
