import './globals.css';

import { Metadata } from 'next';

export const metadata: Metadata = {
  //absolute title = absolute title = dieser Wert wird immer gesetzt und ignoriert die übergoordneten tempaltes
  //default title = für childelemente die keinen title haben, wird dieser wert gesetzt
  //template = für
  title: {
    absolute: '',
    default: 'Next.js Tutorial',
    template: '%s | Text für alle children',
  },
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body>
        <header className='bg-gray-200 p-4'>Header</header>
        {children}
        <footer className='bg-red-200 p-4'>Footer</footer>
      </body>
    </html>
  );
}
